version: "3.8"
services:
  eureka:
    image: iot/eureka-server:latest
    container_name: eureka
    ports: ["8761:8761"]
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: iotdb
    environment:
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot
      POSTGRES_DB: iotdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports: ["3000:3000"]
    depends_on: [db]
    restart: unless-stopped

volumes:
  pgdata:
