services:
  db:
    image: postgres:15
    container_name: postgres-iot
    environment:
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot
      POSTGRES_DB: iotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-iot
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
